name: Release
on:
  push:
    tags:
      - "v*"

env:
  GO_VERSION: "1.18"
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          workdir: ${{ env.git_repo_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
